name: Run unit tests and build Python package
on:
  push:
    branches: ['**']
  release:
    types: [released]
jobs:
  tests_and_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade coveralls mock wheel

    - name: Run unit tests
      run: coverage run --omit=pythesint/tests/* --source=pythesint setup.py test

    - name: Publish coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --service=github

    - name: Build Python package
      if: github.event_name == 'release'
      run: >
        PYTHESINT_RELEASE="${GITHUB_REF#refs/tags/}"
        python setup.py sdist bdist_wheel

    - name: Publish Python package
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # Storing the PyPI URL in the repositories' secrets makes
        # publishing to the test PyPI from forks easy
        repository_url: ${{ secrets.PYPI_REPOSITORY_URL }}
        password: ${{ secrets.PYPI_TOKEN }}
